version: 2.1

parameters:
  nombre:
    type: string
    default: QuillaOne

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hola << pipeline.parameters.nombre >>

workflows:
  workflow1:
    jobs:
      - saluda
