version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hola Bro
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Adios Bro

workflows:
  hello:
    jobs:
      - saluda
      - despidete
